from odoo import api, fields, models
from datetime import timedelta


class ResPartner(models.Model):
    _inherit = 'res.partner'

    sales_period_notification = fields.Integer(
        string='Sales Reminder (days)',
        help='Days after last invoice to trigger a follow-up activity',
        default=0
    )

    def _get_last_invoice_date(self):
        """Return the most recent posted customer invoice date for the commercial partner."""
        self.ensure_one()
        invoice = self.env['account.move'].search([
            ('move_type', 'in', ['out_invoice', 'out_refund']),
            ('state', '=', 'posted'),
            ('commercial_partner_id', '=', self.commercial_partner_id.id),
        ], order='invoice_date desc, id desc', limit=1)
        return invoice.invoice_date or False

    @api.model
    def cron_sales_period_activity(self):
        """Create To-do activities for partners whose (last_invoice + period) >= today."""
        today = fields.Date.context_today(self)

        # Get the To-do activity type
        try:
            todo_type = self.env.ref('mail.mail_activity_data_todo')
        except ValueError:
            # Fallback if reference doesn't exist
            todo_type = self.env['mail.activity.type'].search([('name', '=', 'To-Do')], limit=1)
            if not todo_type:
                return

        # Search for customers with reminder period configured
        partners = self.search([
            ('sales_period_notification', '>', 0),
            ('user_id', '!=', False),
            ('customer_rank', '>', 0),
        ])

        # Cache res_model_id for performance
        res_model_id = self.env['ir.model']._get_id('res.partner')

        for partner in partners:
            last_date = partner._get_last_invoice_date()
            if not last_date:
                continue

            deadline = last_date + timedelta(days=partner.sales_period_notification)

            # Check if deadline has been reached
            if deadline <= today:
                # Check for existing activity to avoid duplicates
                existing = self.env['mail.activity'].search([
                    ('res_model_id', '=', res_model_id),
                    ('res_id', '=', partner.id),
                    ('activity_type_id', '=', todo_type.id),
                    ('user_id', '=', partner.user_id.id),
                    ('date_deadline', '=', deadline),
                ], limit=1)

                if not existing:
                    self.env['mail.activity'].create({
                        'res_model_id': res_model_id,
                        'res_id': partner.id,
                        'activity_type_id': todo_type.id,
                        'user_id': partner.user_id.id,
                        'date_deadline': deadline,
                        'summary': 'Check the customer and schedule it',
                        'note': '<p>Auto-generated by Sales Period Notification.</p>',
                    })
